version: '3'

networks:
  tgl-ms:
    driver: bridge

services:
  ms-emails:
    container_name: ms-emails
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SMTP_HOST: smtp.mailtrap.io
      SMTP_PORT: 2525
      SMTP_USERNAME: f6e3ba7de82208
      SMTP_PASSWORD: 75f5592fd951f4
    ports:
      - 3000:3000
    depends_on:
      - kafka
    networks:
      - tgl-ms

  zookeeper: 
    image: confluentinc/cp-zookeeper:latest
    container_name: ms-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    volumes:
      - ./data/zookeeper/data:/data
      - ./data/zookeeper/datalog:/datalog
    networks:
      - tgl-ms
  
  kafka:
    image: confluentinc/cp-kafka:latest
    user: "0:0"
    container_name: ms-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    # volumes:
    #   - ./data/kafka:/var/lib/kafka/data
    networks:
      - tgl-ms
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1